"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Sandwich.py']
APP_NAME = "Super Sandwich"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist':{
        'CFBundleName':APP_NAME,
        'CFBundleDisplayName':APP_NAME,
        'CFBundleGetInfoString':"Making Sandwiches",
        'CFBundleVersion':'0.1.0',
        'CFBundleShortVersionString':"0.1.0",
        'NSHumanReadableCopyright':u"This is made by me."
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
